SET SERVEROUTPUT ON;

CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(100),
    City VARCHAR2(50),
    LastModified DATE
);

CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    Balance NUMBER(12,2)
);

CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    TransactionType VARCHAR2(20),
    Amount NUMBER(12,2),
    TransactionDate DATE
);

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionDescription VARCHAR2(200)
);

INSERT INTO Customers VALUES (1, 'John Smith', 'New York', SYSDATE);
INSERT INTO Customers VALUES (2, 'Alice Brown', 'Chicago', SYSDATE);

INSERT INTO Accounts VALUES (101, 1, 10000);
INSERT INTO Accounts VALUES (102, 2, 5000);

COMMIT;

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (
        TransactionID,
        ActionDate,
        ActionDescription
    )
    VALUES (
        :NEW.TransactionID,
        SYSDATE,
        'Transaction inserted for Account ID ' || :NEW.AccountID
    );
END;
/

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_balance NUMBER;
BEGIN
    SELECT Balance
    INTO v_balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'DEPOSIT' THEN
        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'Deposit amount must be positive'
            );
        END IF;

        UPDATE Accounts
        SET Balance = Balance + :NEW.Amount
        WHERE AccountID = :NEW.AccountID;

    ELSIF :NEW.TransactionType = 'WITHDRAWAL' THEN
        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(
                -20002,
                'Withdrawal exceeds available balance'
            );
        END IF;

        UPDATE Accounts
        SET Balance = Balance - :NEW.Amount
        WHERE AccountID = :NEW.AccountID;
    END IF;
END;
/

UPDATE Customers
SET City = 'Boston'
WHERE CustomerID = 1;

INSERT INTO Transactions
VALUES (
    1,
    101,
    'DEPOSIT',
    2000,
    SYSDATE
);

INSERT INTO Transactions
VALUES (
    2,
    101,
    'WITHDRAWAL',
    1000,
    SYSDATE
);

COMMIT;

SELECT * FROM Customers;
SELECT * FROM Accounts;
SELECT * FROM Transactions;
SELECT * FROM AuditLog;